package cleaner

import (
	"strings"

	"github.com/Fabianexe/go2jenkins/pkg/entity"
)

func cleanGeneratedFiles(project *entity.Project) *entity.Project {
	for _, p := range project.Packages {
		i := 0
		for i < len(p.Files) {
			f := p.Files[i]
			comments := f.Ast.Comments
			if len(comments) > 0 && strings.HasPrefix(comments[0].Text(), "Code generated by ") {
				p.Files = append(p.Files[:i], p.Files[i+1:]...)
				continue
			}

			i++
		}
	}

	return project
}
