package cleaner

import (
	"log/slog"
	"strings"

	"github.com/Fabianexe/go2jenkins/pkg/entity"
)

func cleanGeneratedFiles(project *entity.Project) *entity.Project {
	slog.Info("Clean generated files")
	for _, p := range project.Packages {
		i := 0
	fileLoop:
		for i < len(p.Files) {
			f := p.Files[i]
			comments := f.Ast.Comments
			packagePos := f.Ast.Package
			for _, c := range comments {
				if c.Pos() > packagePos {
					break
				}

				if strings.Contains(c.Text(), "Code generated by") {
					slog.Debug("Remove generated file", "File", f.FilePath)
					p.Files = append(p.Files[:i], p.Files[i+1:]...)
					continue fileLoop
				}
			}

			i++
		}
	}

	return project
}
